name: 'Создание релиза'
description: 'Создание релиза со списком изменений на основе коммитов по конвенции именования'
author: Vladislav Kuznetsov
inputs:
  gh-token:
    description: Токен GitHub
    required: true
  use-icons:
    description: Флаг, указывающий на то, нужно ли добавлять в заголовки типов изменений соответствующие значки
    required: false
    default: 'true'
  config-path:
    description: Путь до файла конфигурации
    required: false
outputs:
  changelog:
    description: Сгенерированные примечания к выпуску
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: wind
  color: red